### ISSUE TITLE
Need for proper documentation for this Open-Source android app

### ISSUE THREAD

**Issue by ranaaditya** [satyamurti/LetsChat#5]
- Add support of  [dokka](https://github.com/kotlin/dokka)  in the project

**Comment by ch8n** [comment]
hi @ranaaditya I'm interested, let me know your expectations in this?

**Comment by ranaaditya** [comment]
> hi @ranaaditya I'm interested, let me know your expectations in this?

Hi @ch8n , @satyamurti is the lead maintainer of this project, 
But acc. to me for this issue, we need to add support of [DOKKA](https://github.com/Kotlin/dokka) and preferably convert all **build.gradle** files into **build.gradle.kts**. Converting all build files into kotlinscript would be advantageous.

**Comment by ch8n** [comment]
> > hi @ranaaditya I'm interested, let me know your expectations in this?
> 
> Hi @ch8n , @satyamurti is the lead maintainer of this project,
> But acc. to me for this issue, we need to add support of [DOKKA](https://github.com/Kotlin/dokka) and preferably convert all **build.gradle** files into **build.gradle.kts**. Converting all build files into kotlinscript would be advantageous.

@satyamurti Please revert on the same

**Comment by satyamurti** [comment]
Yes!! you can contribute in adding support of Dokka for this project :)
